matrix:
  fast_finish: true

environment:
  global:
    # Environment variables used by astropy helpers
    PYTHON: "C:\\conda"
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
  ANACONDA_TOKEN:
    secure: qPUvwkUOz7231y5T032xtKZk8Xsu3l+Ody1V2kgWIJ1N8w8MX0Q+Gl+vQXbIRYzb

  matrix:
    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      ARCH: "x86"
      platform: "x86"
    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      ARCH: "amd64"
      platform: "x64"
    - PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      ARCH: "x86"
      platform: "x86"
    - PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      ARCH: "amd64"
      platform: "x64"

install:
  # Astropy ci-helpers. See https://github.com/astropy/ci-helpers
  - "git clone git://github.com/astropy/ci-helpers.git"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Install dependencies and build
  - "%CMD_IN_ENV% conda install conda-build anaconda-client -q -y"
  - "%CMD_IN_ENV% conda-build conda.recipe"

build: false

on_success:
  # upload to anaconda cloud
  - cmd: python ci-tools/package-upload.py conda
