defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: continuumio/miniconda3

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            conda install pip -y
            conda install -c lrntct swashes
            pip install pytest pytest-cov codecov
      - run:
          name: run tests
          command: pytest --cov=./ --cov-config .coveragerc --doctest-modules
      - persist_to_workspace:
          root: ~/repo/
          paths:
            - "./*"

  upload:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: build pypi package
          command: python setup.py sdist
      - run:
          name: upload pypi package
          command: |
            pip install twine
            twine upload --skip-existing -u $PYPI_USER -p $PYPI_PWD dist/*
      - run:
          name: build conda package
          command: |
            conda install conda-build anaconda-client -y
            conda config --add channels lrntct
            conda-build conda.recipe
      - run:
          name: upload conda package
          command: python ci-tools/package-upload.py conda


workflows:
  version: 2
  # test every commit, upload only tags
  test-n-upload:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - upload:
          requires:
            - test
          filters:
            tags:
              # should match simple semver
              only: /\d+\.\d+\.\d+/
            branches:
              ignore: /.*/
