{% set pkg_metadata = load_setup_py_data() %}
{% set giturl = "https://github.com/lrntct/pyswashes.git" %}

package:
  name: pyswashes
  version: {{ pkg_metadata.get('version') }}

source:
  git_url: {{ giturl }}
  git_rev: {{ pkg_metadata.get('version') }}

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - pandas
    - swashes

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

about:
  home: {{ pkg_metadata.get('url') }}
  license: {{ pkg_metadata.get('license') }}
  summary: {{ pkg_metadata.get('description') }}

extra:
  recipe-maintainers:
    - lrntct
